name: bouncy_bargain
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #---------------------Packages-------------------------------#
  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Utility Packages
  logger: ^2.5.0
  url_launcher: ^6.3.1
  intl: ^0.19.0
  http: ^1.2.2
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.3
  flutter_native_splash: ^2.4.3
  connectivity_plus: ^6.1.0

  #product specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  #firebase
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  #google
  google_sign_in: ^6.2.2

  #facebook
  flutter_facebook_auth:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #---------------------Assets-------------------------------#
  assets:
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/reviews/
    - assets/logos/

    #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.otf
          weight: 400
        - asset: assets/fonts/coolvetica_regular_italic.otf
          weight: 400
          style: italic