// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Rvvz2sjRpfjhosX9ynu4r6FOtNLJKn0',
    appId: '1:604269957403:web:f292775e8dc32cafbf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    authDomain: 'chit-chat-app-81a16.firebaseapp.com',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
    measurementId: 'G-VC2DN2DV0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpXGkbushli6IIDUE3Ql6rXquCtDcvteo',
    appId: '1:604269957403:android:81c8c978c86bab68bf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSHMmk2jdQznyH99FLjkdZQJ4uX8XQErU',
    appId: '1:604269957403:ios:43e42d88ff968088bf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
    androidClientId: '604269957403-pl4696pf4ufels1a5oojod8tl325m9rl.apps.googleusercontent.com',
    iosClientId: '604269957403-0pl908uvnbev3pc33cb2uus5qpa04vjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Rvvz2sjRpfjhosX9ynu4r6FOtNLJKn0',
    appId: '1:604269957403:web:c168e6c8ef37ad31bf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    authDomain: 'chit-chat-app-81a16.firebaseapp.com',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
    measurementId: 'G-ZWWWZEMKCE',
  );
}
