// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Rvvz2sjRpfjhosX9ynu4r6FOtNLJKn0',
    appId: '1:604269957403:web:6e8eeb21aa0a66f8bf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    authDomain: 'chit-chat-app-81a16.firebaseapp.com',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
    measurementId: 'G-T36LBMZ3V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpXGkbushli6IIDUE3Ql6rXquCtDcvteo',
    appId: '1:604269957403:android:beca6d6b2f290c7bbf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSHMmk2jdQznyH99FLjkdZQJ4uX8XQErU',
    appId: '1:604269957403:ios:69be56c6dadd56e6bf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
    iosClientId: '604269957403-7up8obn484egs2rnfq5l6rgr9el1ppgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bouncyBargains',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSHMmk2jdQznyH99FLjkdZQJ4uX8XQErU',
    appId: '1:604269957403:ios:69be56c6dadd56e6bf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
    iosClientId: '604269957403-7up8obn484egs2rnfq5l6rgr9el1ppgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bouncyBargains',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Rvvz2sjRpfjhosX9ynu4r6FOtNLJKn0',
    appId: '1:604269957403:web:c25210ea84c065cabf03be',
    messagingSenderId: '604269957403',
    projectId: 'chit-chat-app-81a16',
    authDomain: 'chit-chat-app-81a16.firebaseapp.com',
    databaseURL: 'https://chit-chat-app-81a16-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-app-81a16.appspot.com',
    measurementId: 'G-6LH52Q5DBM',
  );
}